version: "3.5"

services:
  mysql:
    image: mysql
    build: ./mysql
    ports:
      - 3306:3306
    restart: always
    hostname: mysql
    environment:
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mysql
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
    command: --sql_mode=""

  bookstore-service:
    build:
      context: ./
      dockerfile: bookstore/Dockerfile
    ports:
      - 8089:8089
    container_name: bookstore-service
    environment:
      MYSQL_HOST: "mysql:3306"
      MYSQL_PORT: 3306
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      SERVER_PORT: ${SERVER_PORT}
